package dev.chronicle.test;

import com.mojang.authlib.GameProfile;
import dev.chronicle.Chronicle;
import dev.chronicle.Settings;
import dev.chronicle.entity.MatterBody;
import dev.chronicle.power.*;
import dev.chronicle.world.MassJobs;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.projectile.Arrow;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.entity.ChestBlockEntity;
import net.minecraft.world.phys.Vec3;
import net.minecraftforge.common.util.FakePlayer;
import net.minecraftforge.gametest.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;

@GameTestHolder(Chronicle.ID)
@PrefixGameTestTemplate(false)
public final class SystemTests {
    private static BlockPos point(GameTestHelper h){return h.absolutePos(new BlockPos(1,2,1));}
    private static ServerPlayer player(GameTestHelper h){var p=new FakePlayer(h.getLevel(),new GameProfile(UUID.randomUUID(),"system-test"));p.setPos(Vec3.atCenterOf(point(h)));Potential.maximize(p);return p;}
    @GameTest(template="empty") public static void moving_entity_hits_another_entity(GameTestHelper h){var p=player(h);var thrown=h.spawn(EntityType.ZOMBIE,new BlockPos(2,3,2));var victim=h.spawn(EntityType.ZOMBIE,new BlockPos(5,3,2));thrown.setNoAi(true);victim.setNoAi(true);float health=victim.getHealth();Physics.launch(p,thrown,new Vec3(2,0,0));thrown.setPos(victim.position());Physics.tick(h.getLevel());h.assertTrue(victim.getHealth()<health,"Momentum collision must damage the intercepted entity");h.assertTrue(thrown.getHealth()<thrown.getMaxHealth(),"Collision transfers work to the thrown body");thrown.discard();victim.discard();h.succeed();}
    @GameTest(template="empty") public static void moving_block_mass_hits_entity(GameTestHelper h){var p=player(h);BlockPos pos=point(h);h.getLevel().setBlock(pos,Blocks.STONE.defaultBlockState(),3);h.getLevel().setBlock(pos.above(),Blocks.GOLD_BLOCK.defaultBlockState(),3);var body=MatterBody.capture(h.getLevel(),List.of(pos,pos.above()),null);var victim=h.spawn(EntityType.ZOMBIE,new BlockPos(5,3,2));float health=victim.getHealth();Physics.launch(p,body,new Vec3(2,0,0));body.setPos(victim.position());Physics.tick(h.getLevel());h.assertTrue(victim.getHealth()<health,"A grouped block body must share entity impact physics");body.discard();victim.discard();h.succeed();}
    @GameTest(template="empty") public static void riding_entity_claims_its_boat(GameTestHelper h){var p=player(h);var boat=h.spawn(EntityType.BOAT,new BlockPos(3,3,3));var rider=h.spawn(EntityType.ZOMBIE,new BlockPos(3,3,3));double emptyMass=Physics.mass(boat);h.assertTrue(rider.startRiding(boat,true),"Fixture rider must mount");var hold=Physics.take(p,rider);h.assertTrue(hold!=null&&hold.entity==boat,"Grabbing a passenger manipulates the root vehicle");h.assertTrue(Physics.mass(boat)>emptyMass,"Composite mass includes occupants");h.assertTrue(Physics.take(p,boat)==null,"A second hold cannot claim the same composite");h.assertTrue(hold.steer(p,boat.position().add(0,1,0),false),"Occupied boat must be steerable");h.assertTrue(rider.getVehicle()==boat,"Grip must preserve riding");hold.close();h.assertFalse(Physics.controlled(rider),"Release clears passenger claims");boat.discard();rider.discard();h.succeed();}
    @GameTest(template="empty") public static void barrier_captures_and_returns_arrows(GameTestHelper h){var p=player(h);var ward=new Ward(p,null,null,false);Vec3 c=ward.center(p);var arrow=new Arrow(h.getLevel(),c.x,c.y,c.z+ward.radius(p)+.5);arrow.setDeltaMovement(0,0,-2);h.getLevel().addFreshEntity(arrow);h.assertTrue(ward.tick(p,false),"Barrier must survive a weak arrow");h.assertTrue(ward.captured()==1&&Physics.controlled(arrow),"Crossing projectile must be suspended");ward.close(p,true);h.assertTrue(!Physics.controlled(arrow)&&arrow.getOwner()==p&&arrow.getDeltaMovement().length()>.5,"Release must physically redirect a captured arrow");arrow.discard();h.succeed();}
    @GameTest(template="empty") public static void plane_geometry_has_fixed_direction(GameTestHelper h){Vec3 center=new Vec3(0,0,0),normal=new Vec3(0,0,1);h.assertTrue(Ward.crossing(Ward.Shape.PLANE,center,normal,4,new Vec3(0,0,2),new Vec3(0,0,-2)).isPresent(),"A front-to-back ray crosses the plane");h.assertTrue(Ward.crossing(Ward.Shape.PLANE,center,normal,4,new Vec3(5,0,2),new Vec3(5,0,-2)).isEmpty(),"A ray outside the finite shield must pass");h.assertTrue(Ward.crossing(Ward.Shape.DOME,center,normal,4,new Vec3(0,-2,6),new Vec3(0,-2,0)).isEmpty(),"Dome underside remains open");h.succeed();}
    @GameTest(template="empty") public static void overwhelming_damage_breaks_barrier(GameTestHelper h){var p=player(h);var ward=new Ward(p,null,null,false);h.assertFalse(ward.absorb(p,1000000),"An overwhelming impact must penetrate");h.assertFalse(ward.tick(p,false),"Spent barrier must fail mechanically");h.succeed();}
    @GameTest(template="empty",timeoutTicks=180) public static void queued_selection_preserves_inventory(GameTestHelper h){var p=player(h);BlockPos start=point(h);for(BlockPos pos:BlockPos.betweenClosed(start,start.offset(3,3,3)))h.getLevel().setBlock(pos,Blocks.STONE.defaultBlockState(),18);h.getLevel().setBlock(start,Blocks.CHEST.defaultBlockState(),3);((ChestBlockEntity)h.getLevel().getBlockEntity(start)).setItem(0,new ItemStack(Items.DIAMOND,7));AtomicReference<MatterBody> result=new AtomicReference<>();MassJobs.capture(p,start,6,64,result::set);h.assertTrue(h.getLevel().getBlockState(start).is(Blocks.CHEST),"Queue submission must not synchronously delete the world");h.succeedWhen(()->{var body=result.get();h.assertTrue(body!=null&&body.mass()==64,"Connected selection must complete as one 64-cell body");h.assertTrue(h.getLevel().getBlockState(start).isAir(),"Source must transfer");var cell=body.cells().stream().filter(c->c.state().is(Blocks.CHEST)).findFirst().orElseThrow();h.assertTrue(cell.data()!=null,"Container NBT must remain in the body");var tag=new CompoundTag();body.saveWithoutId(tag);var restored=Chronicle.MATTER.get().create(h.getLevel());restored.load(tag);h.assertTrue(restored.mass()==64,"Interrupted large body persists every transferred cell");body.discard();restored.discard();});}
    @GameTest(template="empty") public static void flight_does_not_grant_creative_permissions(GameTestHelper h){var p=player(h);boolean mayfly=p.getAbilities().mayfly;var controller=new FlightControl();controller.toggle(p);controller.tick(p,new Intent(Intent.FORWARD|Intent.SPRINT,0));h.assertTrue(p.getAbilities().mayfly==mayfly,"Flight must preserve survival permissions");h.assertTrue(p.isNoGravity()&&p.getDeltaMovement().length()>0,"Flight must apply real self acceleration");controller.close(p);h.assertFalse(p.isNoGravity(),"Flight release restores gravity");h.succeed();}
    @GameTest(template="empty") public static void experienced_casual_force_exceeds_beginner_maximum(GameTestHelper h){var p=player(h);Potential.setLevel(p,1);double early=Potential.force(p);int small=Potential.blocks(p);Potential.setLevel(p,10);h.assertTrue(Potential.force(p)>.25*20*early,"Experienced low output exceeds beginner charged output");h.assertTrue(Potential.blocks(p)>small*100,"Progression increases terrain scale by orders of magnitude");h.succeed();}
    @GameTest(template="empty",timeoutTicks=120) public static void queued_large_placement_preserves_all_cells(GameTestHelper h){var p=player(h);BlockPos start=h.absolutePos(new BlockPos(0,1,0));List<BlockPos> cells=new ArrayList<>();for(BlockPos pos:BlockPos.betweenClosed(start,start.offset(6,6,6))){h.getLevel().setBlock(pos,Blocks.STONE.defaultBlockState(),18);cells.add(pos.immutable());}var body=MatterBody.capture(h.getLevel(),cells,null);h.assertTrue(body!=null&&body.mass()==343,"Fixture is a grouped large mass");h.assertTrue(body.place(start,null),"Large placement must enqueue");h.assertTrue(body.transferring()&&body.isAlive(),"Submission must not synchronously place all blocks");h.succeedWhen(()->{h.assertFalse(body.isAlive(),"Completed body is released only after every cell transfers");for(BlockPos pos:cells)h.assertTrue(h.getLevel().getBlockState(pos).is(Blocks.STONE),"Each original block survives queued placement");});}
    @GameTest(template="empty") public static void palette_snapshot_keeps_actual_block_states(GameTestHelper h){BlockPos start=point(h);h.getLevel().setBlock(start,Blocks.OAK_LOG.defaultBlockState().setValue(RotatedPillarBlock.AXIS,net.minecraft.core.Direction.Axis.X),3);h.getLevel().setBlock(start.east(),Blocks.GOLD_BLOCK.defaultBlockState(),3);var body=MatterBody.capture(h.getLevel(),List.of(start,start.east()),null);var buffer=new net.minecraft.network.FriendlyByteBuf(io.netty.buffer.Unpooled.buffer());var client=Chronicle.MATTER.get().create(h.getLevel());try{body.writeSpawnData(buffer);client.readSpawnData(buffer);h.assertTrue(client.cells().get(0).state().getValue(RotatedPillarBlock.AXIS)==net.minecraft.core.Direction.Axis.X,"Texture-facing properties must survive compact networking");h.assertTrue(client.cells().get(1).state().is(Blocks.GOLD_BLOCK),"Mixed materials survive palette packing");}finally{buffer.release();body.discard();client.discard();}h.succeed();}
    @GameTest(template="empty") public static void right_click_and_precision_input_disarm_a_skeleton(GameTestHelper h){var p=player(h);p.setYRot(0);p.setXRot(0);p.tickCount=1;p.setItemSlot(net.minecraft.world.entity.EquipmentSlot.MAINHAND,new ItemStack(Items.DIAMOND));var skeleton=h.spawn(EntityType.SKELETON,new BlockPos(1,3,4));skeleton.setItemSlot(net.minecraft.world.entity.EquipmentSlot.MAINHAND,new ItemStack(Items.BOW));try{h.assertTrue(Applications.target(p)==skeleton,"Fixture must aim at the skeleton");Concentration.accept(p,new Intent(Intent.ACT,0));Concentration.tick(p);h.assertTrue(Physics.controlled(skeleton),"Right click must grip with an arbitrary item in hand");p.tickCount++;Concentration.accept(p,new Intent(Intent.ACT|Intent.SNEAK|Intent.ATTACK,0));Concentration.tick(p);h.assertTrue(skeleton.getMainHandItem().isEmpty(),"A brief precision squeeze must remove the bow");h.assertTrue(skeleton.isAlive(),"Disarming must happen before crushing damage");var bows=h.getLevel().getEntitiesOfClass(net.minecraft.world.entity.item.ItemEntity.class,skeleton.getBoundingBox().inflate(3),item->item.getItem().is(Items.BOW));h.assertTrue(bows.size()==1&&bows.get(0).getItem().getCount()==1,"The real bow must survive exactly once");for(var bow:bows)bow.discard();h.succeed();}finally{Concentration.release(p);skeleton.discard();}}
}
