package dev.chronicle;

import net.minecraftforge.common.ForgeConfigSpec;

public final class Settings {
    public static final ForgeConfigSpec SPEC;
    public static final ForgeConfigSpec.IntValue MAX_LEVEL, STRUCTURE_LIMIT, TERRAIN_BUDGET, CRYSTAL_RARITY, AWAKEN_TIME;
    public static final ForgeConfigSpec.IntValue FLIGHT_LEVEL, FIELD_LEVEL, SENSE_LEVEL, HEAL_LEVEL, REGION_LEVEL, BURST_LEVEL;
    public static final ForgeConfigSpec.DoubleValue XP_RATE, LEVEL_RATE, AGE_XP, XP_CURVE, CAPACITY, CAPACITY_GROWTH, RECOVERY, OVERALL_STRENGTH;
    public static final ForgeConfigSpec.DoubleValue RANGE, RANGE_GROWTH, MAX_RANGE, FORCE, FORCE_GROWTH, RESISTANCE, HARDNESS, BULLET_CAPACITY, FIELD_RADIUS, FLIGHT_COST, HEAL_RATE;
    public static final ForgeConfigSpec.BooleanValue INVENTORIES, PVP, TERRAIN, MOB_COLLISIONS, HINTS, AURA, GEOMETRY_EFFECTS;
    public static final ForgeConfigSpec.IntValue ARMOR_COOLDOWN, CHOKE_TIME, CRYSTAL_MIN_Y, CRYSTAL_MAX_Y;
    public static final ForgeConfigSpec.IntValue WORLD_EDIT_BUDGET, AREA_LIMIT, INITIAL_BLOCKS, PROJECTILE_BUDGET, BARRIER_CAPTURE_LIMIT, TARGET_LIMIT;
    public static final ForgeConfigSpec.DoubleValue MASS_DENSITY, MATTER_GRAVITY, MATTER_DRAG, COLLISION_DAMAGE, GRIP_STRENGTH, COMPRESSION_DAMAGE, BOSS_RESISTANCE, MAX_COLLISION_DAMAGE, MAX_MASS;
    public static final ForgeConfigSpec.DoubleValue FORCE_SCALING, BLOCK_SCALING, FLIGHT_SPEED, FLIGHT_ACCELERATION, FLIGHT_DRAG, FLIGHT_SPEED_GROWTH, DEFENSE, JUMP_BOOST, KNOCKBACK_DAMPING;
    public static final ForgeConfigSpec.DoubleValue BARRIER_HEALTH, BARRIER_GROWTH, BARRIER_MAX_RADIUS, BARRIER_MAINTENANCE;
    public static final ForgeConfigSpec.BooleanValue SOUNDS, GUN_COMPAT;
    public static final ForgeConfigSpec.DoubleValue OUTPUT_STEP;
    public static final ForgeConfigSpec.DoubleValue TARGET_GROWTH;
    static {
        var b = new ForgeConfigSpec.Builder();
        b.push("growth");
        MAX_LEVEL = b.comment("Ten progression stages; servers can cap progression earlier.").defineInRange("maximumLevel", 10, 1, 10);
        XP_RATE = b.defineInRange("experiencePerEffort", .08, 0., 100.);
        LEVEL_RATE = b.comment("Multiplier for all earned psychokinesis experience; zero disables growth.").defineInRange("levelingRateMultiplier", 1., 0., 100.);
        AGE_XP = b.defineInRange("experiencePerOnlineSecond", .025, 0., 100.);
        XP_CURVE = b.defineInRange("experienceCurve", 45., 1., 100000.);
        CAPACITY = b.defineInRange("initialStrainCapacity", 75., 1., 100000.);
        CAPACITY_GROWTH = b.defineInRange("strainCapacityPerLevel", 7., 0., 10000.);
        RECOVERY = b.defineInRange("restRecoveryPerTick", .45, 0., 1000.);
        b.pop().push("physics");
        OVERALL_STRENGTH = b.comment("Scales reach, force, affected mass, barriers, and large-area manipulation.").defineInRange("overallStrength", 1., .1, 20.);
        OUTPUT_STEP=b.comment("Amount of output changed by each crouch-scroll step. Hotbar scrolling remains enabled.").defineInRange("outputScrollStep",.05,.01,.25);
        RANGE = b.defineInRange("initialReach", 10., 2., 128.);
        RANGE_GROWTH = b.defineInRange("reachPerLevel", .7, 0., 10.);
        MAX_RANGE = b.defineInRange("maximumReach", 96., 2., 256.);
        FORCE = b.defineInRange("initialForce", .18, .01, 10.);
        FORCE_GROWTH = b.defineInRange("forcePerLevel", .025, 0., 10.);
        FORCE_SCALING = b.comment("Multiplicative growth per stage; advanced casual output exceeds beginner maximum output.").defineInRange("forceScalePerLevel", 1.45, 1., 3.);
        RESISTANCE = b.defineInRange("livingResistance", 1., 0., 100.);
        GRIP_STRENGTH = b.defineInRange("gripStrengthMultiplier", 1., .1, 20.);
        BOSS_RESISTANCE = b.defineInRange("bossResistanceMultiplier", 2., .1, 20.);
        MAX_MASS = b.defineInRange("maximumMass", 200000., 1., 10000000.);
        MASS_DENSITY = b.defineInRange("blockDensityMultiplier", 1., .1, 20.);
        COLLISION_DAMAGE = b.defineInRange("collisionDamageMultiplier", 1., 0., 20.);
        MAX_COLLISION_DAMAGE = b.defineInRange("maximumDamagePerImpact", 100., 1., 10000.);
        COMPRESSION_DAMAGE = b.defineInRange("compressionDamageMultiplier", 1., 0., 20.);
        MATTER_GRAVITY = b.defineInRange("releasedMassGravity", .04, 0., 1.);
        MATTER_DRAG = b.defineInRange("releasedMassDrag", .98, .5, 1.);
        HARDNESS = b.defineInRange("cutHardnessPerLevel", .15, 0., 100.);
        BULLET_CAPACITY = b.defineInRange("projectileDamageCapacityPerLevel", .65, 0., 100.);
        STRUCTURE_LIMIT = b.defineInRange("maximumStructureVolume", 32768, 1, 32768);
        TERRAIN_BUDGET = b.defineInRange("maximumChangedBlocksPerAction", 192, 1, 4096);
        WORLD_EDIT_BUDGET = b.comment("Global cell-work budget per dimension/tick shared by extraction and placement jobs.").defineInRange("worldEditBudgetPerTick", 256, 16, 4096);
        AREA_LIMIT = b.defineInRange("maximumSelectionRadius", 24, 1, 32);
        INITIAL_BLOCKS = b.defineInRange("initialManipulatableBlocks", 24, 1, 4096);
        BLOCK_SCALING = b.defineInRange("massScalePerLevel", 2., 1., 4.);
        TARGET_LIMIT = b.defineInRange("maximumSimultaneousTargets", 512, 1, 1024);
        TARGET_GROWTH=b.defineInRange("targetCountGrowthPerStage",1.9,1.,3.);
        INVENTORIES = b.define("carryBlockEntityData", true);
        TERRAIN = b.define("allowTerrainChanges", true);
        PVP = b.define("affectOtherPlayers", true);
        MOB_COLLISIONS = b.define("thrownMobsDamageOthers", true);
        ARMOR_COOLDOWN = b.defineInRange("armorStripCooldownTicks", 600, 20, 72000);
        CHOKE_TIME = b.defineInRange("maximumChokeTicks", 80, 10, 600);
        b.pop().push("sustainedPower");
        FIELD_RADIUS = b.defineInRange("fieldRadius", 4., 1., 32.);
        BARRIER_HEALTH = b.defineInRange("initialBarrierHealth", 32., 1., 10000.);
        BARRIER_GROWTH = b.defineInRange("barrierHealthPerStage", 14., 0., 10000.);
        BARRIER_MAX_RADIUS = b.defineInRange("maximumBarrierRadius", 32., 1., 64.);
        BARRIER_MAINTENANCE = b.defineInRange("barrierMaintenance", .09, 0., 100.);
        PROJECTILE_BUDGET = b.defineInRange("projectileScanBudgetPerTick", 48, 1, 256);
        BARRIER_CAPTURE_LIMIT = b.defineInRange("maximumCapturedProjectiles", 192, 1, 512);
        FLIGHT_COST = b.defineInRange("flightEffortPerTick", .6, .01, 100.);
        FLIGHT_SPEED = b.comment("Blocks per tick at the first stage.").defineInRange("initialFlightSpeed", .35, .05, 5.);
        FLIGHT_SPEED_GROWTH = b.defineInRange("flightSpeedPerStage", .18, 0., 2.);
        FLIGHT_ACCELERATION = b.defineInRange("flightAcceleration", .08, .01, 1.);
        FLIGHT_DRAG = b.defineInRange("flightBraking", .22, .01, .9);
        DEFENSE = b.defineInRange("reinforcementPerStage", .055, 0., .09);
        JUMP_BOOST = b.defineInRange("enhancedJumpPerStage", .035, 0., .5);
        KNOCKBACK_DAMPING = b.defineInRange("knockbackDampingPerStage", .065, 0., .1);
        HEAL_RATE = b.defineInRange("healingPerSecond", .5, 0., 20.);
        b.pop().push("unlocks");
        FLIGHT_LEVEL = b.defineInRange("flight", 4, 1, 10);
        FIELD_LEVEL = b.defineInRange("fields", 3, 1, 10);
        SENSE_LEVEL = b.defineInRange("radar", 5, 1, 10);
        HEAL_LEVEL = b.defineInRange("regeneration", 7, 1, 10);
        REGION_LEVEL = b.defineInRange("largeStructures", 6, 1, 10);
        BURST_LEVEL = b.defineInRange("psionicExplosion", 9, 1, 10);
        b.pop().push("awakening");
        CRYSTAL_RARITY = b.comment("Average newly generated overworld chunks per chamber attempt").defineInRange("chamberRarity", 300, 1, 100000);
        AWAKEN_TIME = b.defineInRange("exposureTicks", 80, 1, 12000);
        CRYSTAL_MIN_Y = b.defineInRange("minimumY", -55, -64, 300);
        CRYSTAL_MAX_Y = b.defineInRange("maximumY", -25, -64, 300);
        b.pop().push("presentation");
        HINTS = b.comment("Vanilla action-bar hints only; no custom HUD").define("controlHints", true);
        AURA = b.comment("Thin translucent prismatic aura; no particles.").define("thinAura", true);
        GEOMETRY_EFFECTS = b.comment("Smooth translucent prismatic barriers, force waves, and psychic explosions.").define("specialEffects", true);
        SOUNDS = b.define("restrainedPowerSounds", true);
        b.pop().push("compatibility");
        GUN_COMPAT = b.define("optionalGunIntegration", true);
        b.pop(); SPEC = b.build();
    }
    private Settings() {}
}
